

services:
  mysql:
    image: mysql:8.0
    container_name: board_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: board
    ports:
      - "3307:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql